### ISSUE TITLE
Aanpassingen

### ISSUE THREAD

**Issue by jorickscheerens** [kendaru/Teachery#10]
Een aantal gewenste aanpassingen:
- onder Timery werkt de Mute-knop niet
- de huidige csv-uploadfunctie werkt alleen met een compleet csv-bestand uit Magister. Het zou fijn zijn als het ook een basic zelfgemaakt csv-bestand mag zijn met daarbij de mogelijkheid om handmatig namen toe te voegen (en te voorzien van bijv. een klassennaam)
- kan er een geluidje of korte animatie worden toegevoegd bij het selecteren van een naam?

Groet, Jorick

**Comment by kendaru** [comment]
csv-uploadfunctie werkt ook met andere csv-bestanden: https://github.com/kendaru/Teachery/commit/56445311ee2262e7e1460c495e4ba9614b68fc99

**Comment by ikzelf01** [comment]
M.B.T Mute. Globale mute button mute alleen (dus geen unmute) Dit zal bijde zowel tick als eind geluid muten. Deze zijn weer apart aan of uit te zetten in setting van de clock. De auto mute onder settings geld alleen voor nieuwe clocken en niet voor de oude. https://github.com/kendaru/Teachery/commit/3fcd222848c3fae8c453cfd8267dee9991c20548

**Comment by ikzelf01** [comment]
Animatie en geluid bij het kiezen van een random naam. https://github.com/kendaru/Teachery/commit/5a9259e3fc66ce9d4a5cab5bc526a28fa36d1c35
